### ISSUE TITLE
Chorus Predict

### ISSUE THREAD

**Issue by Lawerencium** [cally72jhb/vector-addon#1]
{Bug explanation}
For chorusfruit predict, the teleport hotkey doesnt work reliably. It works about 1/4th of the time and otherwise it doesnt teleport the player at all.

{Steps}
1- Download and install meteor and the vector addon
2- Set a teleport hotkey
3- Enable the module
4- Eat a chorusfruit
     - This will show a render where the player will be teleported. 
5- Press the teleport hotkey at any given time
     - This works only close to 1/4th of the time

**Comment by cally72jhb** [comment]
I fixed it.
