### ISSUE TITLE
1.18.2?

### ISSUE THREAD

**Issue by I-Got-You-Dead** [cally72jhb/vector-addon#15]
Is it possible to make this 1.18.2 
pls?

**Comment by QunatumCrafter** [comment]
I agree, i would like this

**Comment by cally72jhb** [comment]
The next release will be for 1.18.2. Only Meteor has not released a full version for 1.18.2, which causes dev-builds sometimes to be unstable.

**Comment by procrafter820** [comment]
@cally72jhb the latest dev build of meteor is stable
Pls release 1.18.2 of vector

**Comment by cally72jhb** [comment]
no
