### ISSUE TITLE
Portal GM

### ISSUE THREAD

**Issue by Lawerencium** [cally72jhb/vector-addon#2]
{Question}
How does the Portal GM module work? As when using the module, I am able to walk around, yet cant break blocks. Whenever someone comes by to the same location, they see me standing inside the portal unable to move. I can not see the players coming near me, yet i can see the edits they do to the world (breaking and placing) and i can hear them. Neither can i see any entities.

{Suggestion}
The module works partially, since the player that stands still in the portal can not be killed. Yet the player in te portal (me) that walks around, cant do anything either. Is there a way to change this so that the player walks out of the portal and can see entities / break blocks etc. 

If this is not possible, is there a way to show an ESP of where entities should be according to the soundlocation? There is a meteor module for sound location and a render of a player at the location of their footsteps already helps a lot. Hopefully there is a way to do that for any sort of entity as there is multiple "footsteps" sounds. Check out Sound Locator in basic Meteor.

Greetings

**Comment by cally72jhb** [comment]
As the module cancles the teleport confirm packets that are send when you leave a portal you arent able to move or place / interact with things, block breaking should still work.

I'll implement a feature that you know where you stand and one to enable sound locating (if it is possible).

**Comment by Lawerencium** [comment]
You said blockbreaking should still work.
It does work clientside, yet not serverside. 

Really do hope the soundlocating esp works. if there is a way to somehow show where an entity would be by overlaying their ESP on the location of the sound of the footsteps, that would be awesome, since then you can practically "see" the entity while you actually cant physically. Checked the reliability of it using the sound locator module, that works just fine and works as it should.

EDIT: Breaking works serverside aswell, but only in proximity of the server-position of the player which makes sense (so around the portal)

**Comment by Lawerencium** [comment]
If possible, add a function to Crystal Aura aswell to use CA on those ESP players / entities. Cause then youve got a module that kills people without being able to get killed yourself

**Comment by cally72jhb** [comment]
The Crystal Aura interacts with blocks too when it places crystals so thats impossible.

**Comment by Lawerencium** [comment]
I think you mean with entities? Since i just thought it wouldnt work because of the player not being able to see entities. 
You can break blocks, so block interacts work?

But yes, i see, CA for this module is not going to work. Just a hype idea I thought of

**Comment by cally72jhb** [comment]
you cant interact at all, so no crystal placement
