### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by QunatumCrafter** [cally72jhb/vector-addon#21]
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: meteordevelopment/meteorclient/addons/GithubRepo
Exit Code: 255

**Comment by cally72jhb** [comment]
Yea I noticed it too, as I started minecraft normally.
I fixed it for the next Version but its more an issue with meteor.

**Comment by QunatumCrafter** [comment]
what new version?

**Comment by QunatumCrafter** [comment]
im on linux
