### ISSUE TITLE
Vector wont work for me :(

### ISSUE THREAD

**Issue by QunatumCrafter** [cally72jhb/vector-addon#22]
These are the mods i have /home/blade/Documents/Minecraft 1.18.2 best/mods/3dskinlayers-fabric-1.4.2-mc1.18.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/alternate-current-mc1.18-1.1.0 (1).jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/appleskin-fabric-mc1.18.1-2.3.0.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/arciotectury.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/balm-fabric-3.0.0+0.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/beautifiedchatclient-fabric_1.18.x-1.0.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/betterbiomeblend-1.18.2-1.3.3-forge.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/better-loading-screen-1.3.1.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/BetterPvP_22.3.1.1_Fabric_1.18.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/bobby-3.1.1.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/cakechomps-fabric-1.4.1-1.18.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/ChunkAnimator-1.18-1.3.3.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/clientcommands-2.6.1.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/cloth-config-6.2.57-fabric.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/Clumps-forge-1.18.2-8.0.0+7.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/collective-fabric-1.18.x-4.26.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/craftingtweaks-fabric-1.18-13.0.0.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/cullleaves-2.3.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/DamageTilt-1.18-forge-0.1.1.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/eating-animation-1.5.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/enchantment-lore-1.2.5+MC1.18-1.18.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/entityculling-fabric-mc1.18-1.5.0.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/Fabric-1.18-SmoothSwapping-0.4.4.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/fabric-api-0.47.9+1.18.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/fallingleaves-1.10.0+1.18.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/farlight-addon.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/firstperson-fabric-2.1.0-mc1.18-pre1.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/ForgeConfigAPIPort-v3.2.0-1.18.2-Fabric.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/Highlighter-1.18-fabric-1.1.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/Iceberg-1.18.2-fabric-1.0.38.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/iris-mc1.18.2-1.2.2-build.32.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/isometric-renders-0.2.12+1.18.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/ItemBorders-1.18-fabric-1.1.5.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/jei-1.18.2-9.5.3.161.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/lambdynamiclights-2.1.0+1.17.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/lazydfu-0.1.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/LegendaryTooltips-1.18.2-fabric-1.2.4.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/litematica-fabric-1.18.2-0.11.0.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/lithium-fabric-mc1.18.2-0.7.9.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/malilib-fabric-1.18.2-0.12.0.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/MeteorAdditions-1.1.1.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/meteor-client-0.4.8-1449.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/meteor-litematica-printer-1.0.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/meteor-rejects-addon-0.2 (1).jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/Meteor-Tweaks.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/minihud-fabric-1.18.2-0.22.0.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/modmenu-3.1.0.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/MoreCosmetics-Fabric-1.18.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/mousewheelie-1.8.3+mc1.18.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/notenoughanimations-fabric-1.4.0-mc1.18-pre1.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/notenoughcrashes-4.1.4+1.18.1-fabric.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/orion-0.1.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/physics-mod-2.6.7-mc-1.18-fabric.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/preciseblockplacing-1.08+1.18.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/PresenceFootsteps-1.5.0.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/reeses_sodium_options-mc1.18.2-1.4.1.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/seedcrackerX-2.12.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/smoke-suppression-1.0.9-1+MC1.18-1.18.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/sodium-extra-mc1.18.2-0.4.1.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/sodium-fabric-mc1.18.2-0.4.1+build.15.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/soundphysics-fabric-1.18.2-1.0.4.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/starlight-1.0.2+fabric.89b8d9f.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/talkbubbles-1.0.1.18.1.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/tanuki-addon-0.1 (1).jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/vector-addon-0.3.1.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/vector-addon-0.3.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/villager-roller-1.2.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/visuality-0.4.2.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/vmp-fabric-mc1.18.2-0.2.0+beta.3.17-all.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/WorldEditCUI-1.18.2+01.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/worldedit-mod-7.2.10.jar
/home/blade/Documents/Minecraft 1.18.2 best/mods/XaerosWorldMap_1.20.6_Fabric_1.18.2.jar

**Comment by cally72jhb** [comment]
send the log please

**Comment by cally72jhb** [comment]
its prob some issue with the same mixins from other mods or you didnt update to meteor 0.4.9 dev-builds

**Comment by erxson** [comment]
try to remove old vector (vector-addon-0.3.1.jar)

**Comment by cally72jhb** [comment]
Try to remove MeteorTweaks and the other addons that offer MultiTask, their mixins aren't working for latest Meteor Client. Im sure its not a vector issue, because noone else had problems running it so far.
