### ISSUE TITLE
[Suggestion] A creative+ module

### ISSUE THREAD

**Issue by The-Nyla** [cally72jhb/vector-addon#23]
A module that lets you stack unstackable items and edit the inventories of shulkers and other storage blocks whilst they are in your inventory by using a ".editcontainer"command. This would only work in creative by editing the NBT of items, but it would be incredibly useful. I was going to suggest a full-featured NBT editor like [Infinity Item Editor](https://www.curseforge.com/minecraft/mc-mods/infinity-item-editor/files), but that would probably take a while since Infinity is for forge (and since there aren't any really good NBT editors for fabric) so an NBT editor would have to be written from scratch.

**Comment by cally72jhb** [comment]
I don't think I can get this done in a while
