### ISSUE TITLE
Compiling the Source code

### ISSUE THREAD

**Issue by AnandBhasme** [cally72jhb/vector-addon#24]
I know I can download the mod and put it in the mods folder but how do I compile the source code and get the mod?
I did gradlew build but that didn't give me a .jar mod in builds folder. Please Help

**Comment by erxson** [comment]
check build/lib folder

**Comment by AnandBhasme** [comment]
> check build/lib folder

There is no "lib" folder inside the build folder after compiling (and not before).

**Comment by erxson** [comment]
send the log

**Comment by erxson** [comment]
just remove vector-addon-main\src\main\java\cally72jhb\addon\mixin\TitleScreenMixin.java and try to build again

**Comment by erxson** [comment]
![image](https://user-images.githubusercontent.com/50082485/165939707-584450db-921d-498b-81b0-0c2534fa7a72.png)

**Comment by AnandBhasme** [comment]
Thanks for that. It worked!
I tried it before, but I messed something up earlier.
