### ISSUE TITLE
.??

### ISSUE THREAD

**Issue by kokqi** [cally72jhb/vector-addon#30]
Pprtalgodmode force me to stuck in certain place, I can't do anything with freecam except chilling with kill aura, kinda useless tbh

**Comment by cally72jhb** [comment]
Thats how the module works, it cancels the teleport confirm packet = if you rubberband you get desynced and as the server requires you to update your position after leaving a portal you need to send that packet, if you don't you'll be invincible at the cost of not being able to see any entities and not being able to move.

**Comment by cally72jhb** [comment]
I would reccoment you to only enable the module when you are entering a portal. Also you can re-sync yourself when rejoining the server
