### ISSUE TITLE
I installed vector-addon,But it doesn't work

### ISSUE THREAD

**Issue by IF-desu** [cally72jhb/vector-addon#32]
Game Version: MC1.19.2
Log:[minecraft-exported-logs-2023-01-04T17-11-03.log](https://github.com/cally72jhb/vector-addon/files/10342765/minecraft-exported-logs-2023-01-04T17-11-03.log)
FabricVersion:0.14.11
Modlist:see log
Vector version:I tried 0.3.5 0.3.6 0.3.7 in turn
Meteor Version:0.51 for 1.19.2
The mod menu shows this mod but the setting GUI of MeteorClient Doesn't show Vector
![D193LRX)7 PJ)@Z84KM`ZX](https://user-images.githubusercontent.com/86994398/210521919-58803d6b-ceb0-4316-996a-b336024f6bae.png)

**Comment by cally72jhb** [comment]
I don't have vector registered to modmenu you could check if it is working by searching for any of its modules in meteor (for example "PacketPlace" or "RubberbandFly")
