### ISSUE TITLE
Crash 1.19.3

### ISSUE THREAD

**Issue by ItsEgmxn** [cally72jhb/vector-addon#36]
when i try to join any server or single player world it crashes

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'meteordevelopment.meteorclient.systems.commands.Command meteordevelopment.meteorclient.systems.commands.Commands.get(java.lang.Class)'

**Comment by GoofyBoi420** [comment]
omg
you are nerd

**Comment by GoofyBoi420** [comment]
its not for 1.19.3 🤓

**Comment by cally72jhb** [comment]
now its for 1.19.4
