### ISSUE TITLE
Crashing my mc error code -1

### ISSUE THREAD

**Issue by ItsLLolly** [cally72jhb/vector-addon#40]
My meteor works but everytime i add vector it crashes my mc with the error code -1 im on 1.19.4 developent

**Comment by Oreeeee** [comment]
Meteor broke addon compatibility, Vector has to update.

**Comment by ItsLLolly** [comment]
wtf does that mean?

**Comment by Oreeeee** [comment]
I have submitted a pull request fixing this issue, which has to be approved by Vector Addon's developer. Now we need to just wait until it gets merged, which might take some time since the dev seems inactive.

**Comment by ItsLLolly** [comment]
alr would u know if it is done or do i ust have to test it every time?
sorry for the very late response

**Comment by Oreeeee** [comment]
@cally72jhb should make a release soon, but I might make a JAR if you need it right now

**Comment by SalmonSnakeD** [comment]
I have the same problem, the crash code is -1 for me too.

The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: meteordevelopment/meteorclient/systems/commands/Command

So we just have to wait for a updated/fixed version?

**Comment by ItsLLolly** [comment]
Yes excactly that error thanks for the excact 1

**Comment by ItsLLolly** [comment]
> @cally72jhb should make a release soon, but I might make a JAR if you need it right now

I don’t need it rn but I would like to have it in the next week or two if possible

**Comment by ItsLLolly** [comment]
> I have the same problem, the crash code is -1 for me too.
> 
> The game crashed whilst initializing game Error: java.lang.NoClassDefFoundError: meteordevelopment/meteorclient/systems/commands/Command
> 
> So we just have to wait for a updated/fixed version?

I would say so

**Comment by TropicLegend** [comment]
I have similar problems with Meteor

**Comment by Oreeeee** [comment]
I have compiled a JAR for the time until Vector's developer merges my fix, temporarily replace Vector Addon with [this](https://github.com/Oreeeee/vector-addon/releases/tag/0.3.8-patched). Alternatively, if you don't trust me, compile the patched version yourself by cloning my repo and compiling from `fix-meteor` branch. Or just wait for official release.

**Comment by ItsLLolly** [comment]
Alr any1 who has same problem I appreciate the comment but ur spamming my email

**Comment by ItsLLolly** [comment]
> I have compiled a JAR for the time until Vector's developer merges my fix, temporarily replace Vector Addon with [this](https://github.com/Oreeeee/vector-addon/releases/tag/0.3.8-patched). Alternatively, if you don't trust me, compile the patched version yourself by cloning my repo and compiling from `fix-meteor` branch. Or just wait for official release.

Thank you I am not at home rn but I will try to use it

**Comment by ItsLLolly** [comment]
Btw oreeee how did u manage to fix it?

**Comment by Oreeeee** [comment]
Location and usage of some Meteor stuff got changed, and I adjusted it to look in the new locations

**Comment by ItsLLolly** [comment]
Ahh thx
