### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by Alex81341** [cally72jhb/vector-addon#42]
meteor client updated to 1.20

**Comment by RewardedIvan** [comment]
#43 i did it already myself

**Comment by FirePlank** [comment]
> #43 i did it already myself

is there a precompiled .jar file that can be used without having to build from source?

**Comment by MrLyyy** [comment]
https://github.com/MrLyyy/vector-addon
I update to 1.20.1

**Comment by tmuaprep** [comment]
> #43 i did it already myself

how to download it?
