### ISSUE TITLE
Update to 1.20.1

### ISSUE THREAD

**Issue by Budgie2500** [cally72jhb/vector-addon#44]
I just realised that this vector-addon might not support 1.20.1, the latest version of minecraft.

**Comment by MrLyyy** [comment]
https://github.com/MrLyyy/vector-addon
I update to 1.20.1

**Comment by dcorbe** [comment]
It doesn't

**Comment by tron1980s** [comment]
bruh i spent 30 minuets to analyze this an now i realize it dont work on new versoins but good news its safe (i think)

**Comment by St0rmster** [comment]
Is Vector on 1.20.1?

**Comment by cally72jhb** [comment]
1.20.4 now
