### ISSUE TITLE
The packetfly is konas

### ISSUE THREAD

**Issue by Doogie13** [cally72jhb/vector-addon#6]
Don't quote me on that :tm:

**Comment by cally72jhb** [comment]
Yes ik

**Comment by cally72jhb** [comment]
still the first public 1.17 / 1.18 version of it ;P

**Comment by master7720** [comment]
STILL a skid

**Comment by cally72jhb** [comment]
idc

**Comment by cally72jhb** [comment]
its the only skidded thing in vector

**Comment by master7720** [comment]
> its the only skidded thing in vector

highly doubt that

**Comment by cally72jhb** [comment]
what else do you think is skidded?

**Comment by master7720** [comment]
prob everything like every other meteor addon

**Comment by cally72jhb** [comment]
why probably? did you even check any module?

**Comment by master7720** [comment]
> why probably? did you even check any module?

no cuz meteor addons are a waste of time
